### ISSUE TITLE
Bug with code tags

### ISSUE THREAD

**Issue by jphoulchand** [neo4j-documentation/knowledge-base#59]
Hi,

I found an issue at the following link: https://neo4j.com/developer/kb/use-java-runtime-11-with-neo4j-3-5-x/
In this case I think a picture is better than 1000 words.

<img width="1434" alt="Screenshot 2020-11-10 at 09 21 57" src="https://user-images.githubusercontent.com/47752149/98660501-49056680-233d-11eb-8a45-78bd4ea16f11.png">

Thanks for looking into this.

Kind regards,
Jérémie

**Comment by Mogztter** [comment]
Hello @jphoulchand 

What browser and version are you using? I cannot reproduce this issue using the latest version of Firefox and Chrome (on Linux). Here's what's I'm seeing:

![result](https://user-images.githubusercontent.com/333276/98678654-30a64380-235f-11eb-9c39-cd22e94ea737.png)

Looking at the HTML, it seems that the syntax highlighting JavaScript library (CodeMirror) didn't run. Do you see any error in the console?

Having said that, even if I explicitly disable JavaScript I can still see the content:

![js-disabled](https://user-images.githubusercontent.com/333276/98679016-add1b880-235f-11eb-9169-5a873d023388.png)

**Comment by jphoulchand** [comment]
Thanks for looking into it.
It works fine with firefox 83:

User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0
OS 	Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64

It also works fine with chrome.
